### ISSUE TITLE
Attempting to import json file in jspm/typescript project results in error TS2307

### ISSUE THREAD

**Issue by JustASquid** [systemjs/plugin-json#9]
Hi,

I'm building a Typescript project using jspm in Webstorm. I'm a newbie to web dev, so I could very easily be missing something obvious here.

I ran `jspm install json` in my project, which seemed to work fine. It appears under dependencies in package.json.

When I try to include a json file in a .ts file in my project, I get `Error TS2307 - Cannot find module`.

The import statement is
`import Data from "../data/data.json!";`

I've also tried

`import Data from "../data/data.json!json";`

But that didn't work either.

`import "../data/data.json!";` works but as near as I can figure won't actually do anything.

The folder structure of my project:

app
--source
----data
------data.json
----[another folder]
------.ts source file attempting to include data.json
config.js
package.json
etc

**Comment by piotrwitek** [comment]
@JustASquid your import is just fine: `import "../data/data.json!";` and the error is emitted by TypeScript compiler. 
It is because ESM import statement don't recognize it as valid module, and because unfortunately TypeScript don't support module loaders yet, so you cannot provide a ambient declaration for it.
There is a specification proposal for wildcard ambient module declaration usable for this usecase and probably it will be implemented in TS 2.0 #https://github.com/Microsoft/TypeScript/issues/6615
As for now you can just ignore the error and your code will be still emitted and working fine, until there is a proper support from TS.

**Comment by JustASquid** [comment]
Ah, all right! Thanks @piotrwitek.
